# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailPartnerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(default=None, max_length=50, null=True)),
                ('business_name', models.CharField(default=None, max_length=100, null=True)),
                ('address_line_1', models.CharField(default=None, max_length=150)),
                ('address_line_2', models.CharField(default=None, max_length=150, null=True)),
                ('city', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('country', models.CharField(default=None, max_length=50)),
                ('pin', models.CharField(default=None, max_length=10, null=True)),
                ('contact_number', models.CharField(default=None, max_length=20, null=True)),
                ('location_latitude', models.DecimalField(decimal_places=7, default=None, max_digits=10, null=True)),
                ('location_longitude', models.DecimalField(decimal_places=7, default=None, max_digits=10, null=True)),
                ('location_string', models.CharField(default=None, max_length=300, null=True)),
                ('strategic_advantage', models.CharField(default=None, max_length=500, null=True)),
                ('retail_location_type', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.CharField(default=None, max_length=100, null=True)),
                ('updated_by', models.CharField(default=None, max_length=100, null=True)),
                ('status', models.IntegerField(default=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retail_partner_info',
                'managed': True,
            },
        ),
    ]
