# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailPartnerCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'retail_partner_category',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='retailpartnerinfo',
            name='retail_partner_category',
            field=models.IntegerField(default=0),
        ),
    ]
